# Kitty Configuration

# Background Opacity
background_opacity 0.85
dynamic_background_opacity yes

# Cursor Trail
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

# Clipboard Mappings (Copy and Paste in Terminal)
map ctrl+c copy_and_clear_or_interrupt
map ctrl+v paste_from_clipboard
map alt+c copy_to_clipboard
map alt+v paste_from_clipboard
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard


# Word Navigation & Deletion Mappings (Works in both Mac and Linux modes)
map ctrl+backspace send_text all \x17
map super+backspace send_text all \x17
map alt+backspace send_text all \x15
map shift+home send_text all \x15
map ctrl+left send_text all \x1b[1;5D
map ctrl+right send_text all \x1b[1;5C
map super+left send_text all \x1b[1;5D
map super+right send_text all \x1b[1;5C



